---

  - name: Install openstack pkgs
    shell: apt-get install "{{item}}" 
    with_items:
        - software-properties-common
  
  - name: Add the apt repo
    shell: add-apt-repository cloud-archive:ocata
#  - shell: apt update && apt dist-upgrade
#  - apt: update_cache=yes upgrade=dist

  - shell: apt-get install -y python-openstackclient 

#  - file: path={{output}} state=touch
