---

  - name: Install openstack pkgs
    shell: apt-get -y install "{{item}}" 
    with_items:
        - software-properties-common
  
  - name: Add the apt repo
    shell: add-apt-repository -y cloud-archive:ocata

  - shell: apt update && apt -y dist-upgrade
    ignore_errors: yes
#  - apt: update_cache=yes upgrade=dist

  - shell: apt-get install -y python-openstackclient 

  - name: create the output path
    shell: "echo {{output_file}} | rev | cut -d'/' -f2-  | rev"
    register: op
  
  - shell: apt-get install -y crudini 

  - file: path={{op.stdout}} state=directory

  - file: path={{output_file}} state=touch
