---

  - name: List Nova services
    shell: |
       openstack compute service list
       openstack catalog list
       openstack image list
       nova-status upgrade check
    environment:
          OS_USERNAME: admin
          OS_PASSWORD: ADMIN_PASS
          OS_PROJECT_NAME: admin
          OS_USER_DOMAIN_NAME: Default
          OS_PROJECT_DOMAIN_NAME: Default
          OS_AUTH_URL: http://{{hostname_controller}}:35357/v3
          OS_IDENTITY_API_VERSION: 3

