---

  - name: Download cirros image
    get_url:
       url: http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
       dest: /tmp
       
  - name: Upload the image to image service
    shell: openstack image create "cirros" \
           --file cirros-0.3.5-x86_64-disk.img \
           --disk-format qcow2 --container-format bare \
           --public
    chdir: /tmp
    environment:
          OS_USERNAME: admin
          OS_PASSWORD: ADMIN_PASS
          OS_PROJECT_NAME: admin
          OS_USER_DOMAIN_NAME: Default
          OS_PROJECT_DOMAIN_NAME: Default
          OS_AUTH_URL: http://controller:35357/v3
          OS_IDENTITY_API_VERSION: 3
 
  - name: Verification
    shell: openstack image list
    register: image_list

  - debug: msg="{{image_list}}"
 
