---

  - name: Create Domain, projects, users and roles 
    shell: "{{item.cmd}}"
    with_items:
        - { cmd: 'openstack project create --domain default --description "Service Project" service' }
        - { cmd: 'openstack project create --domain default --description "Demo Project" demo' }
        - { cmd: 'openstack user create --domain default --password {{keystone.user_password}} demo' }
        - { cmd: 'openstack role create user' }
        - { cmd: 'openstack role add --project demo --user demo user' }
        - { cmd: ' openstack token issue'}
    environment:
          OS_USERNAME: admin
          OS_PASSWORD: ADMIN_PASS
          OS_PROJECT_NAME: admin
          OS_USER_DOMAIN_NAME: Default
          OS_PROJECT_DOMAIN_NAME: Default
          OS_AUTH_URL: http://{{hostname_controller}}:35357/v3
          OS_IDENTITY_API_VERSION: 3
 
 
