---

  - name: Install memcached pkgs
    shell: apt-get -y install "{{item}}" 
    with_items:
        - memcached
        - python-memcache

  - name: Update /etc/memcached.conf with mgmt ip of controller node
    lineinfile: 
       dest: /etc/memcached.conf
       state: present
       regexp: '^-l.*'
       line: "-l {{controller_ip}}"

  - service: name=memcached state=restarted


