---
 
  - name: Update configuration for OVS
    ini_file: dest="{{item.dest}}"
               section="{{item.section}}"
               option="{{item.opt}}"
               value="{{item.value}}"
    with_items:
        - { dest: '/etc/neutron/neutron.conf', section: 'DEFAULT', opt: "core_plugin", value: "ml2" }
        - { dest: '/etc/neutron/neutron.conf', section: 'DEFAULT', opt: "auth_strategy", value: "keystone" }
          
  - openvswitch_bridge:
    bridge: br-provider
    state: present

  - name: Update configuration for openvswitch_agent
    ini_file: dest="{{item.dest}}"
               section="{{item.section}}"
               option="{{item.opt}}"
               value="{{item.value}}"
    with_items:
        - { dest: '/etc/neutron/plugins/ml2/openvswitch_agent.ini', section: 'ovs', opt: "bridge_mappings", value: "provider:br-provider" }
        - { dest: '/etc/neutron/plugins/ml2/openvswitch_agent.ini', section: 'ovs', opt: "local_ip", value: "{{overlay_interface_ip}}" }
        - { dest: '/etc/neutron/plugins/ml2/openvswitch_agent.ini', section: 'agent', opt: "tunnel_types", value: "vxlan" }
        - { dest: '/etc/neutron/plugins/ml2/openvswitch_agent.ini', section: 'agent', opt: "l2_population", value: "True" }
        - { dest: '/etc/neutron/plugins/ml2/openvswitch_agent.ini', section: 'securitygroup', opt: "firewall_driver", value: "iptables_hybrid" }
        - { dest: '/etc/neutron/l3_agent.ini', section: 'DEFAULT', opt: "interface_driver", value: "openvswitch" }
        - { dest: '/etc/neutron/l3_agent.ini', section: 'DEFAULT', opt: "external_network_bridge", value: "br-provider" }

  - name: Restart the Neutron server and OVS agent
    shell: service neutron-openvswitch-agent restart ; service neutron-l3-agent restart

    
